version: "3"

services:
  rabbit:
    image: "rabbitmq:management"
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - 15672:15672
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  service1:
    build: .
    container_name: service1
    restart: always
    environment:
      LOG_LEVEL: INFO
      URI: amqp://${SERVICE1_NAME:-guest}:${SERVICE1_AUTH:-guest}@rabbit:5672/${SERVICE1_NAME:-%2F}
    depends_on:
      - rabbit
    command:
      - sh
      - -c
      - |
        sleep 15
        echo "Starting service..."
        python3 subscriber.py

  service2:
    build: .
    container_name: service2
    restart: always
    environment:
      LOG_LEVEL: INFO
      URI: amqp://${SERVICE2_NAME:-guest}:${SERVICE2_AUTH:-guest}@rabbit:5672/${SERVICE2_NAME:-%2F}
    depends_on:
      - rabbit
    command:
      - sh
      - -c
      - |
        sleep 15
        echo "Starting service..."
        python3 subscriber.py

  publisher:
    build: .
    container_name: publisher
    restart: always
    environment:
      LOG_LEVEL: INFO

      BROKER_HOST: http://rabbit
      BROKER_PORT: 15672
      BROKER_USER: ${RABBIT_USERNAME}
      BROKER_PASS: ${RABBIT_PASSWORD}

      SERVICES: ${SERVICE1_NAME}=${SERVICE1_AUTH};${SERVICE2_NAME}=${SERVICE2_AUTH}
    depends_on:
      - rabbit
    command:
      - sh
      - -c
      - |
        sleep 10
        echo "Starting publisher..."
        python3 broker.py

volumes:
  rabbitmq_data:
    driver: local
